services:
  - type: web
    name: vid-creation-frontend
    env: static
    buildCommand: bun run build
    staticPublishPath: ./dist
    envVars:
      - key: VITE_API_URL
        value: https://vid-creation-api.onrender.com
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
