services:
  - type: web
    name: frontend
    runtime: static
    rootDir: frontend
    buildCommand: bun install && bun run build
    staticPublishPath: ./dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
