openapi: 3.1.0
info:
  title: FastAPI
  version: 0.1.0
paths:
  /auth/google:
    post:
      summary: Google Auth Callback
      operationId: google_auth_callback_auth_google_post
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
  /api/generate-3d-asset:
    post:
      summary: Generate 3D Asset
      description: 'Generate a 3D asset based on a text prompt.


        This endpoint creates a new job for 3D asset generation and returns

        a job ID that can be used to track the generation progress.'
      operationId: generate_3d_asset_api_generate_3d_asset_post
      parameters:
      - name: authorization
        in: header
        required: false
        schema:
          type: string
          title: Authorization
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Generate3DAssetRequest'
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Generate3DAssetResponse'
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
  /api/jobs/{job_id}:
    get:
      summary: Get Job Status
      description: Get the status of a specific job.
      operationId: get_job_status_api_jobs__job_id__get
      parameters:
      - name: job_id
        in: path
        required: true
        schema:
          type: string
          title: Job Id
      - name: authorization
        in: header
        required: false
        schema:
          type: string
          title: Authorization
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/JobStatus'
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
  /api/projects/{project_id}/jobs:
    get:
      summary: Get Project Jobs
      description: Get all jobs for a specific project.
      operationId: get_project_jobs_api_projects__project_id__jobs_get
      parameters:
      - name: project_id
        in: path
        required: true
        schema:
          type: string
          title: Project Id
      - name: authorization
        in: header
        required: false
        schema:
          type: string
          title: Authorization
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/JobStatus'
                title: Response Get Project Jobs Api Projects  Project Id  Jobs Get
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
  /api/jobs:
    get:
      summary: Get User Jobs
      description: Get all jobs for the authenticated user.
      operationId: get_user_jobs_api_jobs_get
      parameters:
      - name: limit
        in: query
        required: false
        schema:
          type: integer
          default: 50
          title: Limit
      - name: authorization
        in: header
        required: false
        schema:
          type: string
          title: Authorization
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/JobStatus'
                title: Response Get User Jobs Api Jobs Get
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
    post:
      summary: Create Job
      description: Create a new job of any supported type.
      operationId: create_job_api_jobs_post
      parameters:
      - name: authorization
        in: header
        required: false
        schema:
          type: string
          title: Authorization
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/JobCreate'
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/JobStatus'
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
  /api/assets/{job_id}:
    get:
      summary: Get Ksplat Asset
      description: Serve a .ksplat file for a specific job.
      operationId: get_ksplat_asset_api_assets__job_id__get
      parameters:
      - name: job_id
        in: path
        required: true
        schema:
          type: string
          title: Job Id
      - name: authorization
        in: header
        required: false
        schema:
          type: string
          title: Authorization
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
  /api/list-gcs-files:
    get:
      summary: List Gcs Files
      description: List all files in the GCS bucket.
      operationId: list_gcs_files_api_list_gcs_files_get
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
  /api/download-gcs-file/{filename}:
    get:
      summary: Download Gcs File
      description: Download a file from GCS by filename.
      operationId: download_gcs_file_api_download_gcs_file__filename__get
      parameters:
      - name: filename
        in: path
        required: true
        schema:
          type: string
          title: Filename
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
  /api/upload-to-gcs:
    post:
      summary: Upload To Gcs
      description: Upload a file to GCS.
      operationId: upload_to_gcs_api_upload_to_gcs_post
      parameters:
      - name: authorization
        in: header
        required: false
        schema:
          type: string
          title: Authorization
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Body_upload_to_gcs_api_upload_to_gcs_post'
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
  /api/webhooks/{job_id}/stream:
    get:
      summary: Stream Job Updates
      description: 'Server-Sent Events (SSE) endpoint for streaming job updates.

        The frontend can connect to this endpoint to receive real-time updates.'
      operationId: stream_job_updates_api_webhooks__job_id__stream_get
      parameters:
      - name: job_id
        in: path
        required: true
        schema:
          type: string
          title: Job Id
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
  /api/webhooks/test:
    post:
      summary: Test Webhook
      description: Test endpoint for webhook notifications.
      operationId: test_webhook_api_webhooks_test_post
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
  /:
    get:
      summary: Root
      operationId: root__get
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
  /health:
    get:
      summary: Health Check
      operationId: health_check_health_get
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
components:
  schemas:
    Body_upload_to_gcs_api_upload_to_gcs_post:
      properties:
        file:
          type: string
          format: binary
          title: File
      type: object
      required:
      - file
      title: Body_upload_to_gcs_api_upload_to_gcs_post
    Generate3DAssetRequest:
      properties:
        prompt:
          type: string
          maxLength: 1000
          minLength: 1
          title: Prompt
          description: Text prompt for 3D asset generation
        project_id:
          type: string
          title: Project Id
          description: Project ID that the asset belongs to
        webhook_url:
          anyOf:
          - type: string
          - type: 'null'
          title: Webhook Url
          description: Optional webhook URL for job status updates
      type: object
      required:
      - prompt
      - project_id
      title: Generate3DAssetRequest
    Generate3DAssetResponse:
      properties:
        job_id:
          type: string
          title: Job Id
          description: Unique identifier for the generated project
        status:
          type: string
          enum:
          - pending
          - processing
          - completed
          - failed
          title: Status
          description: Current status of the asset generation
      type: object
      required:
      - job_id
      - status
      title: Generate3DAssetResponse
    HTTPValidationError:
      properties:
        detail:
          items:
            $ref: '#/components/schemas/ValidationError'
          type: array
          title: Detail
      type: object
      title: HTTPValidationError
    JobCreate:
      properties:
        job_type:
          type: string
          enum:
          - 3d
          - video
          title: Job Type
          description: Type of job to create
        parameters:
          additionalProperties: true
          type: object
          title: Parameters
          description: Job parameters
        webhook_url:
          anyOf:
          - type: string
          - type: 'null'
          title: Webhook Url
          description: Optional webhook URL for notifications
      type: object
      required:
      - job_type
      - parameters
      title: JobCreate
    JobStatus:
      properties:
        job_id:
          type: string
          title: Job Id
          description: Unique job identifier
        project_id:
          type: string
          title: Project Id
          description: Project ID that the job is associated with
        user_id:
          type: string
          title: User Id
          description: User who created the job
        job_type:
          type: string
          enum:
          - 3d
          - video
          title: Job Type
          description: Type of job
        status:
          type: string
          enum:
          - queued
          - processing
          - completed
          - failed
          title: Status
          description: Current job status
        created_at:
          type: string
          format: date-time
          title: Created At
          description: Job creation timestamp
        modified_at:
          type: string
          format: date-time
          title: Modified At
          description: Last update timestamp
        started_at:
          anyOf:
          - type: string
            format: date-time
          - type: 'null'
          title: Started At
          description: When processing started
        completed_at:
          anyOf:
          - type: string
            format: date-time
          - type: 'null'
          title: Completed At
          description: When processing completed
        progress:
          anyOf:
          - type: number
          - type: 'null'
          title: Progress
          description: Progress percentage (0-100)
        result:
          anyOf:
          - additionalProperties: true
            type: object
          - type: 'null'
          title: Result
          description: Job result data
        error:
          anyOf:
          - type: string
          - type: 'null'
          title: Error
          description: Error message if failed
        webhook_url:
          anyOf:
          - type: string
          - type: 'null'
          title: Webhook Url
          description: Webhook URL for notifications
      type: object
      required:
      - job_id
      - project_id
      - user_id
      - job_type
      - status
      - created_at
      - modified_at
      title: JobStatus
    ValidationError:
      properties:
        loc:
          items:
            anyOf:
            - type: string
            - type: integer
          type: array
          title: Location
        msg:
          type: string
          title: Message
        type:
          type: string
          title: Error Type
      type: object
      required:
      - loc
      - msg
      - type
      title: ValidationError
