openapi: 3.1.0
info:
  title: FastAPI
  version: 0.1.0
paths:
  /auth/google:
    post:
      summary: Google Auth Callback
      operationId: google_auth_callback_auth_google_post
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
  /auth/email:
    post:
      summary: Verify Email Auth
      operationId: verify_email_auth_auth_email_post
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
  /api/webhooks/{job_id}/stream:
    get:
      summary: Stream Job Updates
      description: 'Server-Sent Events (SSE) endpoint for streaming job updates.

        The frontend can connect to this endpoint to receive real-time updates.'
      operationId: stream_job_updates_api_webhooks__job_id__stream_get
      parameters:
      - name: job_id
        in: path
        required: true
        schema:
          type: string
          title: Job Id
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
  /api/webhooks/test:
    post:
      summary: Test Webhook
      description: Test endpoint for webhook notifications.
      operationId: test_webhook_api_webhooks_test_post
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
  /api/jobs/{job_id}:
    get:
      summary: Get Job
      description: Get a specific job.
      operationId: get_job_api_jobs__job_id__get
      parameters:
      - name: job_id
        in: path
        required: true
        schema:
          type: string
          title: Job Id
      - name: authorization
        in: header
        required: false
        schema:
          type: string
          title: Authorization
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Job'
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
  /api/jobs/{project_id}:
    get:
      summary: Get Project Jobs
      description: Get all jobs for a specific project and user.
      operationId: get_project_jobs_api_jobs__project_id__get
      parameters:
      - name: project_id
        in: path
        required: true
        schema:
          type: string
          title: Project Id
      - name: limit
        in: query
        required: false
        schema:
          type: integer
          default: 50
          title: Limit
      - name: authorization
        in: header
        required: false
        schema:
          type: string
          title: Authorization
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Job'
                title: Response Get Project Jobs Api Jobs  Project Id  Get
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
  /api/jobs:
    get:
      summary: Get User Jobs
      description: Get all jobs for the authenticated user.
      operationId: get_user_jobs_api_jobs_get
      parameters:
      - name: limit
        in: query
        required: false
        schema:
          type: integer
          default: 50
          title: Limit
      - name: authorization
        in: header
        required: false
        schema:
          type: string
          title: Authorization
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Job'
                title: Response Get User Jobs Api Jobs Get
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
    post:
      summary: Create Job
      description: Create a new job of any supported type.
      operationId: create_job_api_jobs_post
      parameters:
      - name: authorization
        in: header
        required: false
        schema:
          type: string
          title: Authorization
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/JobCreate'
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Job'
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
  /api/jobs/{job_id}/asset-url:
    get:
      summary: Get Job Asset Url
      description: 'Dedicated endpoint to get the signed URL for a completed job''s
        asset.

        This is a separate endpoint from the main job endpoint to avoid bloating the
        job endpoint with too many responsibilities.'
      operationId: get_job_asset_url_api_jobs__job_id__asset_url_get
      parameters:
      - name: job_id
        in: path
        required: true
        schema:
          type: string
          title: Job Id
      - name: authorization
        in: header
        required: false
        schema:
          type: string
          title: Authorization
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AssetUrlResponse'
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
  /:
    get:
      summary: Root
      operationId: root__get
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
  /health:
    get:
      summary: Health Check
      operationId: health_check_health_get
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
components:
  schemas:
    AssetUrlResponse:
      properties:
        signed_url:
          type: string
          title: Signed Url
        asset_id:
          type: string
          title: Asset Id
        filename:
          type: string
          title: Filename
        storage_path:
          type: string
          title: Storage Path
      type: object
      required:
      - signed_url
      - asset_id
      - filename
      - storage_path
      title: AssetUrlResponse
    HTTPValidationError:
      properties:
        detail:
          items:
            $ref: '#/components/schemas/ValidationError'
          type: array
          title: Detail
      type: object
      title: HTTPValidationError
    Job:
      properties:
        job_id:
          type: string
          title: Job Id
          description: Unique job identifier
        project_id:
          type: string
          title: Project Id
          description: Project ID that the job is associated with
        user_id:
          type: string
          title: User Id
          description: User who created the job
        job_type:
          $ref: '#/components/schemas/JobType'
          description: Type of job
        status:
          $ref: '#/components/schemas/JobStatus'
          description: Current job status
        created_at:
          type: string
          format: date-time
          title: Created At
          description: Job creation timestamp
        modified_at:
          type: string
          format: date-time
          title: Modified At
          description: Last update timestamp
        started_at:
          anyOf:
          - type: string
            format: date-time
          - type: 'null'
          title: Started At
          description: When processing started
        completed_at:
          anyOf:
          - type: string
            format: date-time
          - type: 'null'
          title: Completed At
          description: When processing completed
        progress:
          anyOf:
          - type: number
          - type: 'null'
          title: Progress
          description: Progress percentage (0-100)
        result:
          anyOf:
          - additionalProperties: true
            type: object
          - type: 'null'
          title: Result
          description: Job result data
        error:
          anyOf:
          - type: string
          - type: 'null'
          title: Error
          description: Error message if failed
        webhook_url:
          anyOf:
          - type: string
          - type: 'null'
          title: Webhook Url
          description: Webhook URL for notifications
        parameters:
          anyOf:
          - additionalProperties: true
            type: object
          - type: 'null'
          title: Parameters
          description: Parameters for the job
      type: object
      required:
      - job_id
      - project_id
      - user_id
      - job_type
      - status
      - created_at
      - modified_at
      title: Job
    JobCreate:
      properties:
        job_id:
          type: string
          title: Job Id
          description: Unique job identifier
        job_type:
          $ref: '#/components/schemas/JobType'
          description: Type of job to create
        project_id:
          type: string
          title: Project Id
          description: Project ID that the job is associated with
        webhook_url:
          anyOf:
          - type: string
          - type: 'null'
          title: Webhook Url
          description: Optional webhook URL for notifications
        parameters:
          anyOf:
          - additionalProperties: true
            type: object
          - type: 'null'
          title: Parameters
          description: Parameters for the job
      type: object
      required:
      - job_type
      - project_id
      title: JobCreate
    JobStatus:
      type: string
      enum:
      - queued
      - processing
      - completed
      - failed
      title: JobStatus
    JobType:
      type: string
      enum:
      - Object
      - Video
      - Audio
      - Image
      title: JobType
    ValidationError:
      properties:
        loc:
          items:
            anyOf:
            - type: string
            - type: integer
          type: array
          title: Location
        msg:
          type: string
          title: Message
        type:
          type: string
          title: Error Type
      type: object
      required:
      - loc
      - msg
      - type
      title: ValidationError
